# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_REF_NAME"'
cache:
  paths:
    - .m2/repository
    
stages:
  - build
  - install
  - deploy

# ---------- [ALL BRANCHES] ----------
maven-build:
  stage: build
  script:
    - 'mvn clean compile'

# ---------- [BRANCH DEVELOP] ----------
maven-install-develop:
  stage: install
  script:
    - 'mvn install -DskipTests'
  only:
    - develop
maven-deploy-tomcat:
  stage: deploy
  script:
    - "cd ws/"
    - "mvn tomcat7:redeploy"
  only:
    - develop

# ---------- [BRANCH INTEGRATION / RELEASE/*] ----------
maven-install-release:
  stage: install
  script:
    - 'mvn install'
  only:
    - integration
    - /^release.*$/

# ---------- [BRANCHES PRODUCTION] ----------
maven-deploy-production:
  stage: deploy
  script:
    - "mvn deploy"
  only:
    - master
