# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_REF_NAME"'
cache:
  paths:
    - .m2/repository
    
maven-build:
  stage: build
  script:
    - 'mvn clean compile'
  only:
    - develop
