# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_REF_NAME"'
cache:
  paths:
    - .m2/repository
    
stages:
  - build
  - test
  - deploy
    
maven-build:
  stage: build
  script:
    - 'mvn clean compile'

maven-test:
  stage: test
  script:
    - 'mvn test'

maven-deploy:
  stage: deploy
  script:
    - "cd /ws"
    - "mvn tomcat7:redeploy"
  only:
    - develop