# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_REF_NAME"'
cache:
  paths:
    - .m2/repository
    
stages:
  - build
  - install
  - deploy

# ---------- [ALL BRANCHES] ----------
maven-build:
  stage: build
  script:
    - 'mvn clean compile'

# ---------- [BRANCH DEVELOP / INTEGRATION / RELEASE/*] ----------
maven-install-release:
  stage: install
  script:
    - 'mvn install'
  only:
    - develop
    - integration
    - /^release.*$/

# ---------- [BRANCHES PRODUCTION] ----------
maven-deploy-production:
  stage: deploy
  script:
    - "mvn deploy"
  only:
    - master